import { LazyContextLoader } from "../context/lazy-loader.js";
import { MigrationHandler } from "../../../cli/src/migration/migration-handler.js";
import { benchClearCacheTool, benchRunTestTool } from "../../../cli/src/tools.js";
import * as fs from "fs/promises";

/**
 * Production-ready FrappeProgrammerAgent for executing planner-generated steps in a real Frappe/ERPNext environment.
 */

/**
 * Represents a single, actionable instruction generated by the Planner Agent
 * for the Programmer Agent to execute.
 */
export interface PlanStep {
  stepId: number;
  instruction: string;
  actionType: 'MODIFY_CODE' | 'VALIDATE_TEST' | 'FINAL_REVIEW';
  fileChanges?: Record<string, string>;
  appToTest?: string;
  moduleToTest?: string;
  migrationExpected?: boolean;
}


export class FrappeProgrammerAgent {
  private contextLoader = new LazyContextLoader();
  private migrationHandler = new MigrationHandler();
  private static readonly CUSTOM_APP_NAME = "one_fm/one_fm";
  private static readonly MAX_TEST_RETRIES = 3;
  private sandbox: any; 


  constructor(sandbox: any) {
    this.sandbox = sandbox;
  }
  /**
   * Executes a plan step: modifies code, runs migrations, and/or tests as required.
   */
  async executeStep(
    step: PlanStep,
    currentContext: string
  ): Promise<{ filesModified: string[]; migrationLog: string; testResults: { exitCode: number; output?: string } }> {
    // Example: Use the Frappe programmer prompt for LLM/model calls
    // Load additional context for new imports if needed
    const codeToWrite = this.summarizeFileChanges(step);
    const newImports = this.extractImports(codeToWrite);
    for (const importStmt of newImports) {
      const additionalContext = await this.contextLoader.loadOnDemand(
        importStmt,
        this.getCurrentTokenCount(currentContext),
        180000
      );
      if (additionalContext) {
        currentContext += `\n\n${additionalContext}`;
      }
    }

    let writtenFiles: string[] = [];
    let migrationResult: any = { migrationLog: "", success: true };
    let testResult: { exitCode: number; output?: string } = { exitCode: 0 };

    if (step.actionType === "MODIFY_CODE") {
      writtenFiles = await this.writeFilesFromStep(step);
      migrationResult = await this.runMigration(writtenFiles);
      if (!migrationResult.success) {
        throw new Error(
          `Migration failed and rollback attempted. Errors: ${migrationResult.errors?.join("; ")}`
        );
      }
      await this.runTestLoop(step.appToTest || FrappeProgrammerAgent.CUSTOM_APP_NAME, step.moduleToTest);
      testResult = { exitCode: 0 };
    } else if (step.actionType === "VALIDATE_TEST") {
      await this.runTestLoop(step.appToTest || FrappeProgrammerAgent.CUSTOM_APP_NAME, step.moduleToTest);
      testResult = { exitCode: 0 };
    } // FINAL_REVIEW: no action

    return {
      filesModified: writtenFiles,
      migrationLog: migrationResult.migrationLog || "",
      testResults: testResult
    };
  }

  /**
   * Summarizes file changes for context loading (for real use, this could be omitted or replaced).
   */
  private summarizeFileChanges(step: PlanStep): string {
    if (!step.fileChanges) return "";
    return Object.entries(step.fileChanges)
      .map(([path, content]) => `// ${path}\n${content}`)
      .join("\n\n");
  }

  /**
   * Extracts Python import statements for context loading.
   */
  private extractImports(code: string): string[] {
    const importPattern = /from ([\w\.]+) import/g;
    const matches = code.matchAll(importPattern);
    return Array.from(matches, m => `from ${m[1]} import`);
  }

  private getCurrentTokenCount(context: string): number {
    return Math.ceil(context.length / 4);
  }

  /**
   * Writes or merges files as specified in the plan step.
   */
  private async writeFilesFromStep(step: PlanStep): Promise<string[]> {
    if (!step.fileChanges) return [];
    const written: string[] = [];
    for (const [filePath, content] of Object.entries(step.fileChanges)) {
      // Validate file path here if needed
      if (filePath.endsWith('.json')) {
        try {
          const existing = await fs.readFile(filePath, "utf8");
          const existingJson = JSON.parse(existing);
          const newJson = JSON.parse(content);
          if (Array.isArray(existingJson.fields) && Array.isArray(newJson.fields)) {
            const fieldnames = new Set(existingJson.fields.map((f: any) => f.fieldname));
            for (const field of newJson.fields) {
              if (!fieldnames.has(field.fieldname)) {
                existingJson.fields.push(field);
              }
            }
            await fs.writeFile(filePath, JSON.stringify(existingJson, null, 2), "utf8");
          } else {
            await fs.writeFile(filePath, content, "utf8");
          }
        } catch (err) {
          await fs.writeFile(filePath, content, "utf8");
        }
      } else {
        await fs.writeFile(filePath, content, "utf8");
      }
      written.push(filePath);
    }
    return written;
  }

  /**
   * Runs database migrations after code changes.
   */
  private async runMigration(changedFiles: string[]): Promise<import("../../../cli/src/migration/migration-handler.js").MigrationResult> {
    return this.migrationHandler.handlePostCodeChange(changedFiles);
  }

  /**
   * Runs tests for the app, with retries and cache clearing.
   */
  private async runTestLoop(appName: string, module?: string): Promise<void> {
    let attempts = 0;
    let lastError: any = null;
    while (attempts < FrappeProgrammerAgent.MAX_TEST_RETRIES) {
      const siteName = FrappeProgrammerAgent.getSiteName(this.sandbox);
      const clearResult = await benchClearCacheTool.invoke({ site: siteName });
      const clearStderr = (typeof clearResult === 'object' && 'stderr' in clearResult && typeof clearResult.stderr === 'string') ? clearResult.stderr : '';
      const clearError = (typeof clearResult === 'object' && 'error' in clearResult && clearResult.error) ? clearResult.error : '';
      if (!("success" in clearResult) || !clearResult.success) {
        lastError = `Cache clear failed: ${clearStderr || clearError || "Unknown error"}`;
        attempts++;
        continue;
      }
      const testResult = await benchRunTestTool.invoke({ app: appName, module });
      const testOutput = (typeof testResult === 'object' && 'output' in testResult && typeof testResult.output === 'string') ? testResult.output : '';
      const testStderr = (typeof testResult === 'object' && 'stderr' in testResult && typeof testResult.stderr === 'string') ? testResult.stderr : '';
      const testError = (typeof testResult === 'object' && 'error' in testResult && testResult.error) ? testResult.error : '';
      if ("passed" in testResult && testResult.passed) {
        return;
      } else {
        lastError = `Tests failed.\nSTDOUT:\n${testOutput}\nSTDERR:\n${testStderr}\nERROR:\n${testError || ""}`;
        attempts++;
      }
    }
    throw new Error(
      `Tests failed after ${FrappeProgrammerAgent.MAX_TEST_RETRIES} attempts. Last error: ${lastError}`
    );
  }

  /**
   * Returns the Frappe site name to use for bench commands.
   * If a sandbox is present, use its .site property; otherwise, use env or default.
   */
  private static getSiteName(sandbox?: { site?: string }): string {
    if (sandbox && sandbox.site) return sandbox.site;
    return process.env.FRAPPE_SITE_NAME || process.env.SITE_NAME || "onefm";
  }
}


